---
- name: Copy SSL cert
  copy: src="{{ item.value.ssl.cert }}" dest=/etc/nginx/ssl/{{ item.value.ssl.cert | basename }} mode=0640
  with_dict: wordpress_sites
  when: item.value.ssl.enabled | default(False)

- name: Copy SSL key
  copy: src="{{ item.value.ssl.key }}" dest=/etc/nginx/ssl/{{ item.value.ssl.key | basename }} mode=0600
  with_dict: wordpress_sites
  when: item.value.ssl.enabled | default(False)

- name: Create includes.d directories
  file: path="/etc/nginx/includes.d/{{ item.key }}" state=directory mode=0755
  with_dict: wordpress_sites

- name: Create WordPress configuration for Nginx
  template: src="wordpress-site.conf.j2"
            dest="/etc/nginx/sites-available/{{ item.key }}.conf"
  with_dict: wordpress_sites
  notify: reload nginx

- name: Enable WordPress site
  file: src="/etc/nginx/sites-available/{{ item.key }}.conf"
        dest="/etc/nginx/sites-enabled/{{ item.key }}.conf"
        owner=root
        group=root
        state=link
  with_dict: wordpress_sites
  notify: reload nginx
