---
- name: Determine whether to connect as root or admin_user
  local_action: shell ssh -o PasswordAuthentication=no root@{{ inventory_hostname }} "echo root" || echo {{ admin_user }}
  changed_when: false
  register: remote_user

- name: Set remote user for each host
  set_fact:
    ansible_ssh_user: "{{ remote_user.stdout }}"
